### ISSUE TITLE
Cyrillic letters are too wide

### ISSUE THREAD

**Issue by shardeex** [fontworks-fonts/Klee#10]
Hello! I can't use this font because of big white spaces between in cyrillic letters. Latin symbols, digits, etc. are okay.
![image](https://user-images.githubusercontent.com/54213170/164991212-d7a129b5-fe71-4ac1-bf4a-9dcd56e70003.png)

**Comment by kokiabe** [comment]
Hi, @shardeex 
In the countries where Kanji characters are used, including Japan, there is a concept of of full-width and half-width characters. There is no clear rule, but the width of Cyrillic characters in Japanese fonts generally is full-width. This is because the example glyphs in Adobe-Japan1, the de facto standard for Japanese fonts, are full-width.Full-width Cyrillic characters are only used within the Japanese language, not for its language notation.

It is true that some characters have separate sign Unicode code-positions for full-width or half-width characters. Thus, both characters of different widths can be displayed. Unfortunately, this is not the case for the Cyrillic characters.
http://www.unicode.org/charts/PDF/UFF00.pdf

You can freely modify the glyph contours and metrics informations, as these fonts are licensed under the SIL Open Font License.

**Comment by shardeex** [comment]
> You can freely modify the glyph contours and metrics informations, as these fonts are licensed under the SIL Open Font License.

Thank you for fast reply. If I understand you right, I should modify the glyphs myself? Could you recommend a program for doing this? I will be very happy to help with this weird bug.

**Comment by kokiabe** [comment]
I'm sorry,  I have no plans to modify these fonts.
[Source files](https://github.com/fontworks-fonts/Klee/tree/master/sources) are edited using '[Glyphs 2'](https://glyphsapp.com/buy). It may be difficult to edit unless you are a type designer. The build instructions for these fonts are described in [README](https://github.com/fontworks-fonts/Klee).

**Comment by shardeex** [comment]
Thank you for your response. 🥰

**Comment by kokiabe** [comment]
@shardeex 
FYI...
[LxgwWenkaiTC](https://github.com/lxgw/LxgwWenkaiTC)

**Comment by shardeex** [comment]
> @shardeex 
> FYI...
> [LxgwWenkaiTC](https://github.com/lxgw/LxgwWenkaiTC)

It solves the issue, thanks a lot! 🥰
